### ISSUE TITLE
Use SSM, SSMMessages VPC endpoint 

### ISSUE THREAD

**Issue by TejjeT** [aws/amazon-eks-connector#5]
Hello,

Is there a way we could use VPC Endpoints for ssm, ssmmessages ,s3 in the pods instead of reaching out to public endpoints so that companies do not have open their firewall to long list of Amazon ips ?

**Comment by lynnnnnnluo** [comment]
Thank you for bringing up the issue. I believe the answer is you can as long as the service you are using supports Privatelink integration. You could check this [documentation](https://docs.aws.amazon.com/vpc/latest/privatelink/aws-services-privatelink-support.html) for service availability.

Then you can follow this [document](https://docs.aws.amazon.com/vpc/latest/privatelink/create-interface-endpoint.html) to setup VPC endpoints to the corresponding service in your VPC, enable private DNS and your request will be routed through AWS Privatelink.
